// GENERATED by reference/capture-m04-golden.mjs from reference/prototype-m04-etch.html.
// Do not edit by hand; regenerate with the command in that script's header.
// Values are the prototype's own output, kept at full double precision.

export interface GoldenLitho {
  rpm: number;
  source: 'g' | 'i' | 'krf' | 'arf';
  designNm: number;
  dose: number;
  resistThicknessNm: number;
  cdMinNm: number;
  ratio: number;
  printedNm: number;
  scumNm: number;
  taperNm: number;
  status: 'ok' | 'marginal' | 'fail';
}

export type GoldenRecipe =
  | { mode: 'wet'; etchant: 'boe10' | 'boe6' | 'hf49'; timeMin: number }
  | { mode: 'dry'; powerW: number; pressureMTorr: number; timeMin: number };

export interface GoldenEtch {
  id: string;
  litho: { rpm: number; source: 'g' | 'i' | 'krf' | 'arf'; designNm: number; dose: number };
  recipe: GoldenRecipe;
  metrics: {
    printedNm: number;
    cleared: boolean;
    topNm: number;
    bottomNm: number;
    undercutNm: number;
    siLossNm: number;
    resistLeftNm: number;
    sidewallAngleDeg: number;
  };
  /** Fingerprint of the full arrival-time field: cells with finite arrival, and their sum (min). */
  arrival: { finiteCount: number; sumFinite: number };
}

export const GOLDEN_LITHO: readonly GoldenLitho[] = [
  {
    rpm: 3000,
    source: 'i',
    designNm: 800,
    dose: 1,
    resistThicknessNm: 500,
    cdMinNm: 365,
    ratio: 2.191780821917808,
    printedNm: 800,
    scumNm: 0,
    taperNm: 0,
    status: 'ok',
  },
  {
    rpm: 3000,
    source: 'i',
    designNm: 400,
    dose: 1,
    resistThicknessNm: 500,
    cdMinNm: 365,
    ratio: 1.095890410958904,
    printedNm: 400,
    scumNm: 0,
    taperNm: 16.32876712328768,
    status: 'ok',
  },
  {
    rpm: 3000,
    source: 'i',
    designNm: 365,
    dose: 1,
    resistThicknessNm: 500,
    cdMinNm: 365,
    ratio: 1,
    printedNm: 365,
    scumNm: 0,
    taperNm: 24.000000000000004,
    status: 'ok',
  },
  {
    rpm: 3000,
    source: 'i',
    designNm: 300,
    dose: 1,
    resistThicknessNm: 500,
    cdMinNm: 365,
    ratio: 0.821917808219178,
    printedNm: 219.86301369863014,
    scumNm: 148.40182648401833,
    taperNm: 38.24657534246576,
    status: 'marginal',
  },
  {
    rpm: 3000,
    source: 'i',
    designNm: 150,
    dose: 1,
    resistThicknessNm: 500,
    cdMinNm: 365,
    ratio: 0.410958904109589,
    printedNm: 0,
    scumNm: 500,
    taperNm: 71.12328767123289,
    status: 'fail',
  },
  {
    rpm: 3000,
    source: 'i',
    designNm: 800,
    dose: 0.7,
    resistThicknessNm: 500,
    cdMinNm: 365,
    ratio: 2.191780821917808,
    printedNm: 755,
    scumNm: 180.00000000000003,
    taperNm: 0,
    status: 'marginal',
  },
  {
    rpm: 3000,
    source: 'i',
    designNm: 800,
    dose: 1.5,
    resistThicknessNm: 500,
    cdMinNm: 365,
    ratio: 2.191780821917808,
    printedNm: 875,
    scumNm: 0,
    taperNm: 0,
    status: 'marginal',
  },
  {
    rpm: 3000,
    source: 'g',
    designNm: 500,
    dose: 1,
    resistThicknessNm: 500,
    cdMinNm: 581.3333333333333,
    ratio: 0.8600917431192662,
    printedNm: 395.06880733944973,
    scumNm: 116.5902140672782,
    taperNm: 35.19266055045871,
    status: 'marginal',
  },
  {
    rpm: 3000,
    source: 'arf',
    designNm: 150,
    dose: 1,
    resistThicknessNm: 500,
    cdMinNm: 124.51612903225805,
    ratio: 1.2046632124352332,
    printedNm: 150,
    scumNm: 0,
    taperNm: 7.626943005181346,
    status: 'ok',
  },
  {
    rpm: 1500,
    source: 'krf',
    designNm: 300,
    dose: 0.8,
    resistThicknessNm: 707,
    cdMinNm: 185.99999999999997,
    ratio: 1.612903225806452,
    printedNm: 270,
    scumNm: 84.83999999999989,
    taperNm: 0,
    status: 'marginal',
  },
  {
    rpm: 6000,
    source: 'i',
    designNm: 300,
    dose: 0.65,
    resistThicknessNm: 354,
    cdMinNm: 365,
    ratio: 0.821917808219178,
    printedNm: 181.3869863013699,
    scumNm: 274.9884931506849,
    taperNm: 38.24657534246576,
    status: 'marginal',
  },
];

export const GOLDEN_ETCH: readonly GoldenEtch[] = [
  {
    id: 'A',
    litho: {
      rpm: 3000,
      source: 'i',
      designNm: 800,
      dose: 1,
    },
    recipe: {
      mode: 'wet',
      etchant: 'boe6',
      timeMin: 3.3,
    },
    metrics: {
      printedNm: 800,
      cleared: true,
      topNm: 1440,
      bottomNm: 1040,
      undercutNm: 320,
      siLossNm: 0,
      resistLeftNm: 500,
      sidewallAngleDeg: 56.309932474020215,
    },
    arrival: {
      finiteCount: 19600,
      sumFinite: 31205.4524448363,
    },
  },
  {
    id: 'B',
    litho: {
      rpm: 3000,
      source: 'i',
      designNm: 800,
      dose: 1,
    },
    recipe: {
      mode: 'dry',
      powerW: 200,
      pressureMTorr: 30,
      timeMin: 4.6,
    },
    metrics: {
      printedNm: 800,
      cleared: true,
      topNm: 820,
      bottomNm: 800,
      undercutNm: 10,
      siLossNm: 0,
      resistLeftNm: 410,
      sidewallAngleDeg: 88.09084756700362,
    },
    arrival: {
      finiteCount: 39000,
      sumFinite: 784177.0097234047,
    },
  },
  {
    id: 'C',
    litho: {
      rpm: 3000,
      source: 'i',
      designNm: 400,
      dose: 1,
    },
    recipe: {
      mode: 'dry',
      powerW: 80,
      pressureMTorr: 180,
      timeMin: 9,
    },
    metrics: {
      printedNm: 400,
      cleared: true,
      topNm: 920,
      bottomNm: 680,
      undercutNm: 260,
      siLossNm: 0,
      resistLeftNm: 450,
      sidewallAngleDeg: 68.19859051364818,
    },
    arrival: {
      finiteCount: 39000,
      sumFinite: 1330547.9823368215,
    },
  },
  {
    id: 'D',
    litho: {
      rpm: 3000,
      source: 'i',
      designNm: 800,
      dose: 1,
    },
    recipe: {
      mode: 'wet',
      etchant: 'hf49',
      timeMin: 0.12,
    },
    metrics: {
      printedNm: 800,
      cleared: false,
      topNm: 1260,
      bottomNm: 0,
      undercutNm: 230,
      siLossNm: 0,
      resistLeftNm: 500,
      sidewallAngleDeg: 0,
    },
    arrival: {
      finiteCount: 19600,
      sumFinite: 1560.2726222418432,
    },
  },
  {
    id: 'E',
    litho: {
      rpm: 3000,
      source: 'i',
      designNm: 1200,
      dose: 1,
    },
    recipe: {
      mode: 'wet',
      etchant: 'boe10',
      timeMin: 8,
    },
    metrics: {
      printedNm: 1200,
      cleared: true,
      topNm: 1980,
      bottomNm: 1700,
      undercutNm: 390,
      siLossNm: 0,
      resistLeftNm: 500,
      sidewallAngleDeg: 64.98310652189998,
    },
    arrival: {
      finiteCount: 21600,
      sumFinite: 45932.73201337346,
    },
  },
  {
    id: 'F',
    litho: {
      rpm: 3000,
      source: 'i',
      designNm: 800,
      dose: 1,
    },
    recipe: {
      mode: 'dry',
      powerW: 300,
      pressureMTorr: 20,
      timeMin: 14,
    },
    metrics: {
      printedNm: 800,
      cleared: true,
      topNm: 2600,
      bottomNm: 2600,
      undercutNm: 900,
      siLossNm: 130,
      resistLeftNm: 0,
      sidewallAngleDeg: 90,
    },
    arrival: {
      finiteCount: 39000,
      sumFinite: 339830.11154175515,
    },
  },
  {
    id: 'G',
    litho: {
      rpm: 3000,
      source: 'i',
      designNm: 400,
      dose: 0.7,
    },
    recipe: {
      mode: 'dry',
      powerW: 150,
      pressureMTorr: 100,
      timeMin: 6,
    },
    metrics: {
      printedNm: 355,
      cleared: false,
      topNm: 0,
      bottomNm: 0,
      undercutNm: 0,
      siLossNm: 0,
      resistLeftNm: 220,
      sidewallAngleDeg: 0,
    },
    arrival: {
      finiteCount: 39000,
      sumFinite: 1235922.7077233798,
    },
  },
  {
    id: 'H',
    litho: {
      rpm: 3000,
      source: 'i',
      designNm: 300,
      dose: 1,
    },
    recipe: {
      mode: 'wet',
      etchant: 'boe6',
      timeMin: 3.3,
    },
    metrics: {
      printedNm: 219.86301369863014,
      cleared: false,
      topNm: 0,
      bottomNm: 0,
      undercutNm: 0,
      siLossNm: 0,
      resistLeftNm: 460,
      sidewallAngleDeg: 0,
    },
    arrival: {
      finiteCount: 8742,
      sumFinite: 0,
    },
  },
  {
    id: 'I',
    litho: {
      rpm: 6000,
      source: 'g',
      designNm: 600,
      dose: 1,
    },
    recipe: {
      mode: 'dry',
      powerW: 250,
      pressureMTorr: 60,
      timeMin: 8,
    },
    metrics: {
      printedNm: 600,
      cleared: true,
      topNm: 720,
      bottomNm: 680,
      undercutNm: 60,
      siLossNm: 40,
      resistLeftNm: 80,
      sidewallAngleDeg: 86.18592516570965,
    },
    arrival: {
      finiteCount: 39000,
      sumFinite: 454302.859168775,
    },
  },
  {
    id: 'J',
    litho: {
      rpm: 3000,
      source: 'i',
      designNm: 1200,
      dose: 1,
    },
    recipe: {
      mode: 'dry',
      powerW: 120,
      pressureMTorr: 40,
      timeMin: 3,
    },
    metrics: {
      printedNm: 1200,
      cleared: false,
      topNm: 1260,
      bottomNm: 0,
      undercutNm: 30,
      siLossNm: 0,
      resistLeftNm: 480,
      sidewallAngleDeg: 0,
    },
    arrival: {
      finiteCount: 39000,
      sumFinite: 1036763.153666397,
    },
  },
];
